remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Top Tag"
description: "An Android implementation to collect Elk herd numbers and predict tag draw odds per Game Management Unit."
author:
  name: "Lee Scroggins"
  email: lee_scroggins@yahoo.com
# Do not change the following line.
  copyright: true


