remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "New Mexico Draw Prediction"
description: "Collect Elk herd numbers per game management unit, tag draw numbers, and harvest reports to increase odds of drawing a hunting tag.!"
author:
  name: "Lee Scroggins"

# Do not change the following line.
  copyright: true
